version: '3.5'
services:
    # ReadTheDocs
    documentation:
        # image: anthonyrawlinsuom/lfmc-docs
        image: anthonyrawlinsuom/lfmc-docs
        command: serve -a 0.0.0.0:8800
        restart: on-failure
        networks:
          - frontend
        ports:
          - "8800:8800"
        volumes:
          - ./documents:/documents
networks:
    frontend:
        driver: bridge